home:
  path: /
  defaults: { _controller: 'Diary\Controllers\IndexController::indexAction' }

posts:
  path: /posts
  defaults: { _controller: 'Diary\Controllers\IndexController::allAction' }

posts_complete:
  path: /posts/finish/{id}
  defaults: { _controller: 'Diary\Controllers\IndexController::completeAction' }


hello:
  path: /hello/{name}
  defaults: { _controller: 'Diary\Controllers\IndexController::helloAction' }
